version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: SixLabors.ImageSharp
    versions:
    - 1.0.2
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
